<div class="base-page lighter">

	<div class="formulario-section">

		    <aside>
       	 		<h1 class="blog">Creación de Proyecto</h1>
    		</aside>

			<a  href="javascript:void(0)"  
	            onclick="$('#proyecto-form').submit();" 
	            class="btn btn-success pull-right btn-save">Guardar</a>

        <form id="proyecto-form" action="<?php print($this->url->get("proyecto/store")) ?>" method="post" data-type="ajax" class='form'>
        	<br><br>
        	<div class="row">
        		<div class="col-md-5 col-md-offset-2">
        			<div class="form-group">
		        		<label for="nombre">Nombre</label>
		        		<input type="text" id='nombre' name='nombre' class="form-control" placeholder='Nombre proyecto'>
		        	</div>
        		</div>

        		<div class="col-md-3">
        			<div class="form-group">
		        		<label for="nombre">Código</label>
		        		<input type="text" id='codigo' name='codigo' class="form-control" placeholder='Cód. Proyecto'>
		        	</div>
        		</div>
        	</div>
			
			<br>

        	<div class="row">
        		<div class="col-md-8 col-md-offset-2">
        			<label for="descripcion">Descripción</label>
        			<textarea name="descripcion" id="descripcion" class='form-control' rows='5' placeholder="Descripción proyecto"></textarea>
        		</div>
        	</div>

        	<br>

        	<div class="row">
        		<div class="col-md-4 col-md-offset-2">
        			<div class="form-group">
		        		<label for="jefep">Jefe Proyecto</label>
		        		<select name="jefep" id="jefep" class='form-control chosen'>
		        			<option value=''>Seleccione</option>
		        			<?php
		        				foreach ($pcData['users'] as $usuario) {
		        					echo "<option value='".$usuario->id."'>".$usuario->name."</option>";
		        				}
		        			?>
		        		</select>
		        	</div>
        		</div>

        		<div class="col-md-2">
        			<label for="area">Área</label>
	        		<select name="area" id="area" class='form-control chosen'>
	        			<option value=''>Seleccione</option>
	        			<?php
	        				foreach ($pcData['areas'] as $area) {
	        					echo "<option value='".$area->id."'>".$area->nombre."</option>";
	        				}
	        			?>
	        		</select>
        		</div>

        		<div class="col-md-2">
        			<div class="form-group">
		        		<label for="tecnologia">Tecnología</label>
		        		<select name="tecnologia" id="tecnologia" class='form-control chosen'>
		        			<option value=''>Seleccione</option>
		        			<?php
		        				foreach ($pcData['tecnologias'] as $tecnologia) {
		        					echo "<option value='".$tecnologia->id."'>".$tecnologia->nombre."</option>";
		        				}
		        			?>
		        		</select>
		        	</div>
        		</div>
        	</div>	        	

        </form>

	</div>
</div>