 <div class="">
            <!-- Main Sidebar -->
            <div id="sidebar" style="margin-top: 59px;">
                <!-- Wrapper for scrolling functionality -->
                <div id="sidebar-scroll">
                    <!-- Sidebar Content -->
                    <div class="sidebar-content">
                        <!-- Brand -->
						<a href="index.php" class="sidebar-brand" style="height:50px">
							<i class="gi gi-user"></i>
							<span class="sidebar-nav-mini-hide"><strong>Zenta</strong>SGPP</span>
						</a>
                        <!-- END Brand -->

                        <!-- Sidebar Navigation -->
                        <ul class="sidebar-nav">

                          <li class="sidebar-header">

                                    <span class="sidebar-header-title">Menú</span>
                            </li>                        
                            <li>
                                <a href="<?php print($this->url->get('asignacion/general')) ?>" class="<?php print($sideBarSel=='estado'?'active':'') ?>"><i class="gi gi-log_book"></i><span class="sidebar-nav-mini-hide"> Vista General </span></a>
                            </li>

                            <li>
                                <a href="<?php print($this->url->get('asignacion/proyectos')) ?>" class="<?php print($sideBarSel=='estado'?'active':'') ?>"><i class="gi gi-log_book"></i><span class="sidebar-nav-mini-hide"> Asignación Proyectos</span></a>
                            </li>   

                            <li>
                                <a href="<?php print($this->url->get('registro/ingresar')) ?>" class="<?php print($sideBarSel=='estado'?'active':'') ?>"><i class="gi gi-log_book"></i><span class="sidebar-nav-mini-hide"> Registro</span></a>
                            </li>   

                            <li>
                                <a href="<?php print($this->url->get('actividad/listar')) ?>" class="<?php print($sideBarSel=='estado'?'active':'') ?>"><i class="gi gi-log_book"></i><span class="sidebar-nav-mini-hide"> Lista actividades</span></a>
                            </li>                            
                        </ul>
                        <!-- END Sidebar Navigation -->
                    </div>
                    <!-- END Sidebar Content -->
                </div>
                <!-- END Wrapper for scrolling functionality -->
            </div>
            <!-- END Main Sidebar -->
</div>



