		<div id="passChange" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
			<div class="modal-dialog">
					<form action="<?php print $this->url->get('ajax/changePass')?>" method="post" enctype="multipart/form-data" class="form-horizontal" data-type="ajax">			
                <div class="modal-content">

                    <!-- Modal Body -->
                    <div class="modal-body">
						<fieldset id="fieldSetChangePass">
							<legend>Cambia tu password</legend>
							<div class="form-group">
								<label class="col-md-4 control-label" for="userPassword">Nuevo Password</label>
								<div class="col-md-8">
								<input type="password" id="userPassword" name="userPassword" class="form-control" placeholder="****" value="">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label" for="userConfirmPassword">Confirma Nuevo Password</label>
								<div class="col-md-8">
									<input type="password" id="userConfirmPassword" name="userConfirmPassword" class="form-control" placeholder="****" value="">
								</div>
							</div>
						</fieldset>		
							
						<fieldset id="fieldSetLogout" style="display:none;">
							<legend>Debes volver a iniciar sesión.</legend>
							<a href="<?php print $this->url->get('logout')?>" 
							   class="btn btn-warning" 
							   style="margin: 0 auto;
									  display: block;
									  max-width: 10em;"
							>Logout</a>
						</fieldset>			
                    </div>
                    <!-- END Modal Body -->
					<div class="modal-footer">
						<button id="cambiarPassButton" type="submit" class="btn btn-sm btn-success">Cambiar</button>
					</div>							
					
                </div>
                </form>
            </div>
		</div>


