<div id="error-container">
    <div class="error-options">
        <h3><i class="fa fa-chevron-circle-left text-muted"></i> <a  style="color:#2b669a" href="<?php print $this->url->get("/") ?>">Ir a Inicio</a></h3>
    </div>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-center">
            <h1 class="animation-hatch" style="color:#2b669a"><i class="fa fa-times"></i> 403</h1>
            <h2 class="h3" style="color: #3b3f40;">Oops, no tienes permiso para acceder a esta sección.</h2>
        </div>
    </div>
</div>