		<table id="tablaVistaGeneral" class="table table-vcenter table-striped">
			<thead>
				<tr>
					<th></th>
					<?php foreach($pcData['weeks'] as $mondayWeek){ ?>
						<th class="text-center"><h5> <?php print($mondayWeek) ?><h5></th>
					<?php }?>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($pcData['personas'] as $persona): ?>
					<tr class="text-center">
						<td class="col-personas"><?php print($persona['nombres'])?><br><?php print($persona['apellido_paterno']) ?></td>
						<?php foreach ($pcData['weeks'] as $mondayWeek): ?>
							<?php if (isset($pcData['data'][$mondayWeek][$persona['rut']])): ?>
								<?php $dataCompleta = $pcData['data'][$mondayWeek][$persona['rut']] ?>
								<?php $data = reset($dataCompleta); ?>

								<td>
									<a 	href="javascript:void(0)" 
									 
										data-val="rut=<?php print($persona['rut']) ?>&fecha=<?php print($mondayWeek) ?>&ps_id=<?php print($data['prsn_smna_id']) ?>" 
										class="widget widget-asignacion widget-hover-effect1 tabla-proyecto"
										data-toggle="tooltip"
										data-original-title="
											<?php foreach ($dataCompleta as $proy) {
												print($proy['proy_nombre'].':'.$proy['hh_porcentaje_asignadas'].'%&#10');			
											} ?>">

										<?php
											if($data['hh_total_porcentaje_asignadas'] == 100){

												$color_label = "background_color_green";
											}else{
												$color_label = "background_color_red";
											}
										?>

										<div class='cinta_proyecto themed-background-<?php print($data['proy_color']); ?>'></div>

										<div class="widget-simple <?php echo $color_label; ?> ">
											<div class="widget-content widget-content-light">
												<?php print($data['hh_total_porcentaje_asignadas']) ?>%	
											</div>
										</div>
									</a>
								</td>
							<?php else: ?>
								<td>
									<a href="javascript:void(0)" data-val="rut=<?php print($persona['rut']) ?>&fecha=<?php print($mondayWeek) ?>&pm_id=<?php print(isset($pcData['data']['prsn_mes_id'])?$pcData['data']['prsn_mes_id']:'') ?>" class="widget widget-asignacion widget-hover-effect1 tabla-proyecto" >
										<div class='cinta_proyecto background_color_red'></div>
										<div class="widget-simple themed-background-night ?> background_color_red">
											<div class="widget-content widget-content-light ">
												0%	
											</div>
										</div>
									</a>
								</td>
							<?php endif ?>
						<?php endforeach ?>				
					</tr>
				<?php endforeach ?>

			</tbody>
			
		</table>