<div class="content-width">
	<div class="widget" style="background-color: #f6f6f6;">
		<div class="widget-simple" style="padding-top: 12x;padding-bottom: 12px;" id="sticker" >
			<div class="row">
				<div class="col-xs-8" style="padding-left: 10px;">
					<h2 style="margin:0px;font-size: 20px;">
						Evaluando a:<i class="gi gi-user"></i> <strong><?php print $personaEvaluar['nombres']." ".$personaEvaluar['apellido_paterno']." ".$personaEvaluar['apellido_materno'] ?></strong> &nbsp;<i class="gi gi-group"></i>&nbsp; <?php print  $personaEvaluar['area']?></span>
					</h2>
				</div>
				<div class="col-xs-4 text-right" style="padding-right: 5px;">
				
					<div class="btn-group btn-group-xs">
						<?php if(isset($_POST['evaluador'])){?>
							<a data-ajax="false" href="<?php print $this->url->get("evaluacion/listadoComite") ?>" data-action="<?php print $this->url->get("evaluacion/listadoComite") ?>" data-val="evaluador=<?php print($_POST['evaluador'])?>" class="btn btn-warning" style="margin-right: 10px;height: 27px;line-height: 1.9;"> <i class="gi gi-left_arrow"></i> Volver a Comite</a>
						<?php }else{?>
							<a href="" class="btn btn-warning" style="margin-right: 10px;height: 27px;line-height: 1.9;"> <i class="gi gi-left_arrow"></i> Volver</a>
						<?php }?>
						<a id="submitBtn" class="btn btn-primary pull-right" style="height: 27px;line-height: 1.9;"><i class="gi gi-floppy_saved"></i> Guardar Evaluación</a>
					</div>				
				
					
				</div>
			</div>
		</div>
	</div>
					
	<div class="col-lg-12 center-block">
		<div class="row">
				<form id="evalForm" action="<?php print $this->url->get('ajax/createEvaluacionPersona') ?>" data-type="ajax">
					<table class="tableSinPadding " style="width:100%;">
						<thead>
							<tr>
								<th style="padding: 5px auto !important;">Categoría</th>
								<th>Preguntas</th>
								<th width="2%">Porcentaje</th>
								<th width="15%"></th>
								<th width="2%" class="text-center">Poderación</th>
							</tr>
						</thead>

						<?php $cont = 0; //solo para style ?>
						<?php foreach ($evaluacion as $item):?>
							<?php $id=$item['id_tipo'];?>
							<tbody>
								<tr class="formCategoriaTipo<?php  print($item['id_tipo']%2==0?'A':'B')?>">
									<td ROWSPAN=5 style="padding: 10px !important;vertical-align:middle" ><?php print($item['nombre_tipo']) ?></td>
									<td style="padding: 0px !important;"></td>
									<td style="padding: 0px !important;"></td>
									<td ROWSPAN=5 style="padding: 0px !important;vertical-align:middle" >
										<textarea id="obs-<?php print $item['id_tipo']?>" name="obs-<?php print $item['id_tipo']?>" rows="9" class="form-control" placeholder="Observación Categoría"><?php print(isset($dataForm['obs-'.$id])?$dataForm['obs-'.$id]:''); ?></textarea>									
									</td>
									<td id="pondPreview-<?php print $item['id_tipo']?>" ROWSPAN=5 style="vertical-align:middle;" class="text-center"> <?php print(isset($dataForm['pond-'.$id])?$dataForm['pond-'.$id]:'0'); ?>%</td>
									<td class="hidden">
										<input id="pond-<?php print $item['id_tipo']?>" name="pond-<?php print $item['id_tipo']?>" class="hidden" type="text" value="<?php print(isset($dataForm['pond-'.$id])?$dataForm['pond-'.$id]:'0'); ?>">
									</td>
							   </tr>
							<?php foreach ($item['preguntas'] as $pregunta): ?>
								<?php $idpreg=$pregunta['id_pregunta'];?>
								<tr class="r<?php  print($cont%2==0?'owCategoriaTipoA':'')?>">
									<td style="padding: 0px 0px 0px 10px !important;"><?php print_r($pregunta['pregunta']) ?></td>
									<td width="5%">
										<input 	id="preg-<?php print $pregunta['id_tipo'] ?>-<?php print $pregunta['id_pregunta'] ?>"
												name="preg-<?php print $pregunta['id_tipo'] ?>-<?php print $pregunta['id_pregunta'] ?>"
												data-tipo="<?php print $pregunta['id_tipo'] ?>" data-pregunta="<?php print $pregunta['id_pregunta'] ?>"
												oninput="limitCheck(this)"
												value="<?php print(isset($dataForm['preg-'.$id.'-'.$idpreg])?$dataForm['preg-'.$id.'-'.$idpreg]:''); ?>"
												class="form-control" type="Number" min="0" max="100" value="0" maxlength="3">
									</td>
								</tr>
								<?php $cont += 1; ?>
							<?php endforeach; ?>

							</tbody>
						<?php endforeach; ?>
					</table>
					<input id="rutEvaluado" name="rutEvaluado" class="hidden" type="text" value="<?php print($personaEvaluar['rut']) ?>">
					<input id="rutEvaluador" name="rutEvaluador" class="hidden" type="text" value="<?php print($personaEvaluador['rut']) ?>">
				</form>
		</div>
	</div>
</div> <!--"content-width"-->
<script>
	
	$( "#submitBtn" ).click(function() {
	  $( "#evalForm" ).submit();
	});

	$('[id^="preg-"]').on('change', function(){
		var calc = 0;
		var cant = 0;

		$('[id^="preg-'+$(this).data("tipo")+'"]').each(function(){
			if($.isNumeric($(this).val())){
				calc = parseInt($(this).val()) + calc;
			}
			cant += 1;
		});
		if($.isNumeric(calc)){
			$("#pond-"+$(this).data('tipo')).val(Math.floor(calc/cant));
			$("#pondPreview-"+$(this).data('tipo')).html(Math.floor(calc/cant)+"%");
		}
	});

	function limitCheck(object) {
	    if (object.value > 100){
      		object.value = 100;
	    }
      	if (object.value < 0){
      		object.value = 0;
	    }
		$(object).trigger('change');
	}
</script>