	            	<div class="widget">
						<div class="widget-simple" style="padding-top: 12x;padding-bottom: 12px;">
							<div class="row text-center">
								<div class="col-lg-5">
									<?php if (isset($pcData['vistaPropias'])){ ?>
										<h2 style="margin:0px;font-size: 25px;">Evaluar Personal</h2>
									<?php }else{ ?>
										<h2 style="margin:0px;font-size: 25px;">Selección de Personal</h2>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>

<?php if (!isset($pcData['vistaPropias'])): ?>

            <div class="form-group">
                <div class="col-md-6">
                    <input id="searchRow" type="text" class="form-control" placeholder="Buscador de Personas">             
                </div>
            </div>
<?php endif ?>


<!-- Widgets Row -->
		<!-- tabla solicitudes -->

        <div id="bodyEvaluacion" class="col-md-12">
            
            <?php echo $this->view->render('evaluacion/tablaPersonas',array('pcData'=>$pcData));?>

        </div>

        <!--/tabla solicitudes -->
    <script>
        function postCarga()
        {
            $('#passChange').modal({
                backdrop: 'static',
                keyboard: false
            });                 
        }
    </script>