            <table id="tablaPersonas" class="table table-vcenter table-striped small-title">
                <thead>
                    <tr>
                        <th><h3><b>Evaluado</b></h3></th>
						<?php 
						
						foreach($pcData['lista'] as $prop) {$val = $prop;break;} 
							foreach($val as $k => $v){
						?>
						<th><?php print($v->nombre_tipo)?> </th>
						<?php }?>
						<th>Total</th>
                    </tr>
                </thead>			
				<tbody>
					<?php 
						foreach($pcData['lista'] as $key => $val){
					?>
					<?php foreach($val as $k => $v){$v0=$v;break;}?>
					<tr>
						<td>
							<a href="<?php print $this->url->get("ajax/loadEvaluacionPersona") ?>" data-action="<?php print $this->url->get("ajax/loadEvaluacionPersona") ?>" data-val="rut=<?php print($v0->rut_evaluado) ?>&evaluador=<?php print($v0->rut_evaluador) ?>"><?php print($key)?></a>
						</td>
						<?php 
							$puntaje=0;
							foreach($val as $k => $v){
							$puntaje = $puntaje +	$v->puntaje;
						?>
						<td><?php print($v->puntaje)?> %</td>
						<?php }?>
						<th>
						<?php print((int)($puntaje/9))?> %
						</th>						
					</tr>
					<?php }?>
				</tbody>
			</table>