<?php
//print_r($pcData['lista']);


?>
	<div class="widget">
		<div class="widget-simple" style="padding-top: 12x;padding-bottom: 12px;">
			<div class="row text-center">
				<div class="col-lg-12">
					<h2 style="margin:0px;font-size: 25px;"><b>Comite de Evaluación</b></h2>
				</div>
			</div>
		</div>
	</div>

	<div class="row h3">
		<form id="searchForm" action="<?php print $this->url->get("ajax/listadoComite") ?>" method="post" data-type="ajax">	
		<div class="col-md-6" style="margin-left:5px">
			<b>Evaluador</b>
			<select name="evaluador" class="select-chosen" data-placeholder="Seleccione Evaluador.." data-submit="true">
				<option/>
				<?php foreach($pcData['lev'] as $ke=>$e){?>
				<option value="<?php print($ke)?>" <?php print($pcData['evSel']==$ke?'selected':'')?>><?php print($e)?></option>
				<? }?>
			</select>
		</div>
		</form>
	</div>	

	<div class="center-block">
        <div class="table-responsive" id="mesatabla">
<?php echo $this->view->render('evaluacion/mesaTabla',array('pcData'=>$pcData));?>
		</div>
	</div>
