
<div class="center-block">
        <div class="table-responsive">
            <table id="tablaPersonas" class="table table-vcenter table-striped small-title">
                <thead>
                    <tr>
                        <th>Rut</th>
                        <th>Nombre</th>				
                        <th>Área</th>
						<?php if (!isset($pcData['vistaPropias']) ){ ?>
                        <th>Correo</th>
                        <?php }else{ ?>
						<th>Avance</th>
                        <?php } ?>
                        <th style="width: 150px;" class="text-center">Acción</th>
                    </tr>
                </thead>
                <tbody>

                <?php foreach ($pcData['personas'] as $persona) {?>
                    <tr> 
                   		<td><?php print($persona->rut) ?></td>
                   		<td><?php print($persona->nombres) ?> <?php print($persona->apellido_paterno." ".$persona->apellido_materno) ?></td>
                    	<td>
                    		<?php print($persona->area) ?>
                    	</td>
						<?php if (!isset($pcData['vistaPropias']) ){ ?>
                    	<td>
                    		<?php print($persona->correo) ?>
                    	</td>
                        <?php }else{ ?>
                    	<td class="<?php print($persona->estadoClass) ?>">
                    		<?php print($persona->estadoEva) ?>
                    	</td>							
                        <?php } ?>
                        <td class="text-center" style="width:12em;">
                            <?php if (isset($pcData['vistaPropias']) ){ ?>
                            <form action="<?php print $this->url->get("ajax/excelEvaluacion") ?>" class="form-group" target="_blank" method="POST">
                                <div class="btn-group btn-group-xs">
                                    <a href="<?php print $this->url->get("ajax/loadEvaluacionPersona") ?>" data-action="<?php print $this->url->get("ajax/loadEvaluacionPersona") ?>" data-val="rut=<?php print($persona->rut) ?>"  class="btn btn-default"><i class="hi hi-ok"></i> Evaluar </a>
                                    <?php if($persona->estadoEva == 'Evaluación Completa'){ ?>
                                    
                                        <input type="hidden" name="rut" value="<?php print($persona->rut) ?>">
                                        <button type="submit" class="btn btn-warning btn-xs"><i class="fa fa-file-excel-o"></i> </button>  
                                    
                                    <?php }else{ ?>
                                    <a href="<?php print $this->url->get("ajax/deleteLiderPersona") ?>" data-action="<?php print $this->url->get("ajax/deleteLiderPersona") ?>" data-val="rut=<?php print($persona->rut) ?>" data-delete="¿Realmente desea liberar a este integrante de su listado propio?" class="btn btn-warning"><i class="hi hi-remove"></i> Liberar </a>                                        
                                    <?php } ?>                             
                                </div>
                            </form> 
                            <?php }else{ ?>
                                <div class="btn-group btn-group-xs">
                                    <?php if ($this->auth->getIdentity()['id'] == $persona->lider_id){ ?>
                                        <a class="btn btn-default btn-success"><i class="gi gi-check"></i> Seleccionado </a>
                                    <?php }else{ ?>
                                        <a href="<?php print $this->url->get("ajax/updateLiderPersona") ?>" data-action="<?php print $this->url->get("ajax/updateLiderPersona") ?>" data-delete="¿Está seguro que desea agregar esta persona a su lista propia?" data-val="rut=<?php print($persona->rut) ?>" class="btn btn-default"><i class="gi gi-check"></i> Seleccionar </a>         
                                    <?php } ?>

                                </div>                                
                            <?php } ?>
                        </td>
                    </tr>
                 <?php } ?>
                </tbody>
            </table>
        </div>
</div>


    <?php if (isset($jsScript)): ?>
        <script>
            <?php print($jsScript) ?>
        </script>
    <?php endif ?>
