<div class="base-page lighter">

	<div class="formulario-section">

		    <aside>
       	 		<h1 class="blog">Creación de usuario</h1>
    		</aside>

			<a  href="javascript:void(0)"  
	            onclick="$('#users-form').submit();" 
	            class="btn btn-success pull-right btn-save">Guardar</a>

        <form id="users-form" action="<?php print($this->url->get("usuarios/store")) ?>" method="post" data-type="ajax" class='form'>
        	<br><br>
        	<div class="row">
        		<div class="col-md-4 col-md-offset-2">
        			<div class="form-group">
		        		<label for="nombre">Nombre</label>
		        		<input type="text" id='nombre' name='nombre' class="form-control" placeholder='Nombre' >
		        	</div>
        		</div>

        		<div class="col-md-4">
        			<div class="form-group">
		        		<label for="email">Email</label>
		        		<input type="text" id='email' name='email' class="form-control" placeholder='Email' >
		        	</div>
        		</div>
        	</div>
			
			<br>

        	<div class="row">
        		<div class="col-md-4 col-md-offset-2">
        			<label for="rut">RUT</label>
        			<input name="rut" id="rut" class='form-control' placeholder="RUT" >
        		</div>

        		<div class="col-md-4">
        			<div class="form-group">
		        		<label for="rol">Rol</label>
		        		<select name="rol" id="rol" class='form-control select-chosen'>
		        			<option value='0'>Seleccione</option>
		        			<?php
		        				foreach ($pcData['roles'] as $rol) {

		        					echo "<option value='".$rol->id."'>".$rol->nombre."</option>";
		        				}
		        			?>
		        		</select>
		        	</div>
        		</div>
        	</div>
	
			<br>

        	<div class="row">

        		<div class="col-md-4 col-md-offset-2">
        			<div class="form-group">
		        		<label for="pass">Contraseña</label>
		        		<input type="password" id='pass' name='pass' class="form-control" placeholder='Contraseña' >
		        	</div>
        		</div>

        		<div class="col-md-4">
        			<div class="form-group">
		        		<label for="pass2">Confirmar contraseña</label>
		        		<input type="password" id='pass2' name='pass2' class="form-control" placeholder='Confirmar contraseña' >
		        	</div>
        		</div>
        	</div>

        </form>

	</div>
</div>