<?php
	$user = $pcData['usuario'];		
?>
<div class="base-page lighter">

	<div class="formulario-section">
		
		<div class="row">
			<div class="col-md-6 col-md-offset-2">
				<aside>
			        <h1 class="blog">Edición de usuario</h1>
			    </aside>
			</div>

			<div class="col-md-2">

				<a  href="javascript:void(0)"  
            		onclick="$('#users-form').submit();" 
            		class="btn btn-success pull-right btn-save">Editar</a>
			</div>
		</div>
			    

			

        <form id="users-form" action="<?php print($this->url->get("usuarios/update")) ?>" method="post" data-type="ajax" class='form'>
        	<br><br>

        	<input type="hidden" name="user_id" value='<?php echo $user->id; ?>'>

        	<div class="row">
        		<div class="col-md-5 col-md-offset-2">
        			<div class="form-group">
		        		<label for="nombre">Nombre</label>
		        		<input type="text" id='nombre' name='nombre' class="form-control" placeholder='Nombre' value='<?php echo $user->name;?>'>
		        	</div>
        		</div>

        		<div class="col-md-3">
        			<div class="form-group">
		        		<label for="email">Email</label>
		        		<input disabled type="text" id='email' name='email' class="form-control" placeholder='Email' value='<?php echo $user->email;?>'>
		        	</div>
        		</div>
        	</div>
			
			<br>

        	<div class="row">
        		<div class="col-md-4 col-md-offset-2">
        			<label for="rut">RUT</label>
        			<input name="rut" id="rut" class='form-control' placeholder="RUT" value="<?php echo $user->rut;?>">
        		</div>

        		<div class="col-md-4">
        			<div class="form-group">
		        		<label for="rol">Rol</label>
		        		<select name="rol" id="rol" class='form-control chosen'>
		        			<option value='0'>Seleccione</option>
		        			<?php
		        				foreach ($pcData['roles'] as $rol) {

		        					if($user->rol_id == $rol->id){
		        						$selected = "selected";
		        					}else{
		        						$selected = '';
		        					}

		        					echo "<option value='".$rol->id."' $selected>".$rol->nombre."</option>";
		        				}
		        			?>
		        		</select>
		        	</div>
        		</div>

        		

        	</div>

        	<br>
      	

        </form>
 	</div>
 </div>

<div class="row">
	<div class="col-md-2 col-md-offset-2">
		<a  href="<?php print $this->url->get("usuarios") ?>"  
			class="btn btn-warning btn-back pull-left"><i class="fa fa-reply"></i> Volver</a>				
	</div>
</div> 