<div class="base-page lighter">

	<div class="formulario-section">
		

		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<aside>
			        <h1 class="blog">Listado de usuarios</h1>
			    </aside>
			</div>
		</div>

		
		<form action="<?php echo $this->url->get('usuarios'); ?>" method='GET' id='frm'>
			<div class="row">

				<div class="col-md-3 col-md-offset-1">

					<div class="form-group">
						<label for="name">Nombre</label>
						<input type="text" name='name' class="form-control" placeholder='Nombre Proyecto' value="<?php echo (isset($_GET['name']))?$_GET['name']:'' ?>">
					</div>

				</div>

				<div class="col-md-3">
					<div class="form-group">
						<label for="email">Email</label>
						<input type="text" id='email' name='email' class='form-control' placeholder='email@email.com' value="<?php echo (isset($_GET['email']))?$_GET['email']:'' ?>">
					</div>
				</div>

				<div class="col-md-2">
					<div class="form-group">
						<label for="">&nbsp;</label>
						<button type='submit' class='btn btn-default form-control'>Buscar</button>
					</div>
				</div>

				<div class="col-md-2">
					<div class="form-group">
						<label for="">&nbsp;</label>
						<a href="<?php echo $this->url->get('usuarios/create'); ?>" class='btn btn-success form-control'>Nuevo</a>
					</div>
				</div>
			</div>

			<br><br>
				
			
			<div class="col-md-10 col-md-offset-1">
				
				<hr>
				<div class="table-responsive">
					<table class="table table-striped">
						
						<thead>
							<th>ID</th>
							<th>Nombre</th>
							<th>Email</th>
							<th>RUT</th>
							<th>Rol</th>
							<th>Activo</th>
							<th>Acción</th>
						</thead>

						<tbody>
							<?php
								foreach ($pcData['page']->items as $usuario) {

									if($usuario->delete){
										$class_delete = 'deleted';
									}else{
										$class_delete = '';
									}

									echo "<tr id='tr_".$usuario->id."' class='{$class_delete}'>";
									echo "<td>".$usuario->id ."</td>";
									echo "<td>".$usuario->name ."</td>";
									echo "<td>".$usuario->email ."</td>";
									echo "<td>".$usuario->rut."</td>";
									echo "<td>".$usuario->rol->nombre."</td>";

									if($usuario->delete == 0) $estado = "Sí";
									else $estado = "No";
									echo "<td id='estado_{$usuario->id}'>".$estado."</td>";
									echo "<td>";

									/*if($this->AccesoAcl->tienePermiso('profile', 'usuarios'))
									{
										echo "	<a class='btn btn-warning' href='".$this->url->get('usuarios/profile/').$usuario->id ."'>
													<i class='fa fa-newspaper-o'></i>
												</a>";
					                }*/

									if($this->AccesoAcl->tienePermiso('edit', 'usuarios'))
									{
										echo "	<a class='btn btn-warning' href='".$this->url->get('usuarios/edit/').$usuario->id ."'>
													<i class='fa fa-pencil-square-o'></i>
												</a>";
					                }
									

					                if($usuario->delete)
					                {
										if($this->AccesoAcl->tienePermiso('activa', 'usuarios'))
										{		
											echo "	<button type='button' class='btn btn-warning activa' data-id='".$usuario->id."'>
														<i class='fa fa-thumbs-o-up'></i>
													</button>";
										}

									}else{

										if($this->AccesoAcl->tienePermiso('delete', 'usuarios'))
										{		
											echo "	<button type='button' class='btn btn-warning delete' data-id='".$usuario->id."'>
														<i class='fa fa-times'></i>
													</button>";
										}
									}


										
								
									echo "</td>";
								}
							?>
						</tbody>
					</table>
				</div>


				

					<?php

						if(isset($pcData['page'])){
							$url = '?';

							if(isset($_GET['nombre'])){
								$url .= "&nombre=".$_GET['nombre'];
							}else{
								$url .= "nombre=";
							}

							if(isset($_GET['email'])){
								$url .= "&email=".$_GET['email'];
							}else{
								$url .= "&email=";
							}

							# solo mostramos la paginación si el numero de paginas es mayor a 1
							if( $pcData['page']->total_pages > 1)
							{
								echo "<a href='".$this->url->get("usuarios")."'>Primera</a> ";
								echo "<a href='".$this->url->get("usuarios").$url."&page=".$pcData['page']->before."'>Anterior</a> ";
								echo "<a href='".$this->url->get("usuarios").$url."&page=".$pcData['page']->next."'>Siguiente</a> ";
								echo "<a href='".$this->url->get("usuarios").$url."&page=".$pcData['page']->last."'>Ultima</a> ";
								echo "<BR>Estas en la página ", $pcData['page']->current, " de ", $pcData['page']->total_pages; 

							}
						}
					?>
			</div>
		</form>
	</div>
</div>
	