<div class="base-page lighter">
	<div class="header-user-edit">
		Perfil
		<small><i class="fa fa-caret-right"></i> Configuración de cuenta</small>
	</div>
	<hr>
	<div class="row">
		<div class="col-xs-4">
		</div>

		<div class="col-xs-6">
			<div class="" style="padding: 0px; ">
				<form id="editProfileForm" action="<?php print($this->url->get('usuarios/editProfile')) ?>" method="post" enctype="multipart/form-data" class="form-horizontal my-form" data-type="ajax">
					<input type="hidden" id="userId" name="userId" class="form-control" value="<?php print(isset($pcData['userProfile']['id'])?$pcData['userProfile']['id']:'') ?>">
					<div class="row">
						<div class="col-xs-8">
							<fieldset>
								<div class="form-tittle">Información básica</div>
								<div class="form-group">
									<label class="col-md-5 control-label">Nombre Completo *</label>
									<div class="col-md-7">
										<input type="text" id="userNombre" name="userNombre" class="form-control" value="<?php print(isset($pcData['userProfile']['name'])?$pcData['userProfile']['name']:'') ?>">
									</div>
								</div>
								<div class="form-group" >
									<label class="col-md-5 control-label" for="userEmail">Email *</label>
									<div class="col-md-7">
										<input type="email" id="userEmail" name="userEmail" class="form-control" value="<?php print(isset($pcData['userProfile']['email'])?$pcData['userProfile']['email']:'') ?>">
									</div>
								</div>
							</fieldset>

							<fieldset >
								<div class="form-tittle">Cambia tu password</div>
								<div class="form-group">
									<label class="col-md-5 control-label" for="user-password">Nuevo Password</label>
									<div class="col-md-7">
									<input type="password" id="userPassword" name="userPassword" class="form-control" placeholder="****">
									</div>
								</div>
								<div class="form-group">
									<label class="col-md-5 control-label" for="user-repassword">Confirma Nuevo Password</label>
									<div class="col-md-7">
										<input type="password" id="userConfirmPassword" name="userConfirmPassword" class="form-control" placeholder="****">
									</div>
								</div>
							</fieldset>
							<button onClick="$('#editProfileForm').submit();" type="button" class="btn btn-sm btn-default pull-right">Guardar cambios</button>
						</div>
					</div>
				</form>
			</div>
		</div>

		<div class="col-xs-2">

		</div>
	</div>
</div>

				



		
		
		
												